stages:
  filter_1:
    cmd: python src/process_dataset.py data/dataset.index data/dataset_filtered_1.index --min_duplicate=2
    deps:
    - data/dataset.index
    outs:
    - data/dataset_filtered_1.index

